# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/DhruvArora96/TitanicML/blob/master/main.ipynb
"""

import pandas as pd

url = "https://raw.githubusercontent.com/DhruvArora96/TitanicML/master/test.csv"
test_df = pd.read_csv(url)
url  ="https://raw.githubusercontent.com/DhruvArora96/TitanicML/master/train.csv"
train_df = pd.read_csv(url)

train_df.pop("Name")
train_df.pop("Ticket")
train_df.pop("Cabin")

train_df=train_df.replace({"male":0,"female":1})

train_df=train_df.replace({"S":0,"C":1,"Q":2})

train_df=train_df.dropna()

sv=train_df.pop("Survived")

train_df["Survived"]=sv

features=list(train_df.columns[1:8])
features
X=train_df[features]
Y=train_df["Survived"]

from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf.fit(X, Y)

def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("dt.dot", 'w') as f:
        export_graphviz(tree, out_file=f,feature_names=feature_names)

    command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")

from sklearn.tree import DecisionTreeClassifier, export_graphviz

visualize_tree(clf, features)

export_graphviz(clf,)